### ISSUE TITLE
setup.sql is invisible

### ISSUE THREAD

**Issue by Hjertesvikt** [wolfborg/Kanji2000-Website#9]
Hi Derek,
Congratulations for putting this project on Github. 
Maybe it's me but I couldn't find the setup.sql file. I found it  buried in your commits here:
https://github.com/wolfborg/Kanji2000-Website/blob/b18da70b3818acfa1ac9fb9f67fe7c10f1f856f5/setup.sql
Best,
Jean-Pierre

**Comment by wolfborg** [comment]
Ah yes, I'm not sure what happened to that but it must've been accidentally removed at some point when we were working on the project. I added it back in now.

It looks like there's changes I need to make to get this site working in php7, since I think this was made in php5 and used mcrypt during the process of hashing passwords. I'll make a separate issue for that, but setup.sql is back in the project now.

Thanks a lot!

**Comment by wolfborg** [comment]
Ah, I realized why we removed it. It had to do with the fact that we added new parts to the database and we went to put in a new setup.sql file but we forgot to. I've now added those in and updated the project.
